module next(
    input [1:0] handle,//判定是旋转(0)，左移(1)，右移(2),下降（3）四种操作中哪一个；
    input [4:0] blocks,//判定是19种方块中哪一种；
    input [3:0] i,//中心方块行坐标；
    input [4:0] j,//中心方块列坐标；
    input start,
    input clk,//正常时钟信号；
    input clk0,//专门给下落的时钟信号；
    output reg handle_finish,//返回方块是否到底；
    output reg [4:0] new_block,//返回旋转变化后的方块种类；
    output reg [3:0] new_i,//返回变化后的中心行；
    output reg [4:0] new_j, //返回变化后的中心列；
    input [9:0] game0,game1,game2,game3,game4,game5,game6,game7,game8,game9,
    input [9:0] game10,game11,game12,game13,game14,game15,game16,game17,game18,game19,
    input [9:0] game20,game21,game22,game23,
    output reg [9:0] game0_1,game1_1,game2_1,game3_1,game4_1,game5_1,game6_1,game7_1,game8_1,game9_1,
    output reg [9:0] game10_1,game11_1,game12_1,game13_1,game14_1,game15_1,game16_1,game17_1,game18_1,game19_1,
    output reg [9:0] game20_1,game21_1,game22_1,game23_1
);
    
    reg [9:0] j_2;
    reg [9:0] j_1;
    reg [9:0] j0;
    reg [9:0] j1;
    reg [9:0] j2;
    reg [9:0] j3;
    reg handle_finish_1=0;
    reg [4:0] new_block_1;
    reg [3:0] new_i_1;
    reg [4:0] new_j_1;
    always@(posedge clk or posedge clk0)
    begin
        case(j-2)
            5'd0:j_2<=game0;
            5'd1:j_2<=game1;
            5'd2:j_2<=game2;
            5'd3:j_2<=game3;
            5'd4:j_2<=game4;
            5'd5:j_2<=game5;
            5'd6:j_2<=game6;
            5'd7:j_2<=game7;
            5'd8:j_2<=game8;
            5'd9:j_2<=game9;
            5'd10:j_2<=game10;
            5'd11:j_2<=game11;
            5'd12:j_2<=game12;
            5'd13:j_2<=game13;
            5'd14:j_2<=game14;
            5'd15:j_2<=game15;
            5'd16:j_2<=game16;
            5'd17:j_2<=game17;
            5'd18:j_2<=game18;
            5'd19:j_2<=game19;
            5'd20:j_2<=game20;
            5'd21:j_2<=game21;
            5'd22:j_2<=game22;
            5'd23:j_2<=game23;
            endcase
            case(j-1)
            5'd0:j_1<=game0;
            5'd1:j_1<=game1;
            5'd2:j_1<=game2;
            5'd3:j_1<=game3;
            5'd4:j_1<=game4;
            5'd5:j_1<=game5;
            5'd6:j_1<=game6;
            5'd7:j_1<=game7;
            5'd8:j_1<=game8;
            5'd9:j_1<=game9;
            5'd10:j_1<=game10;
            5'd11:j_1<=game11;
            5'd12:j_1<=game12;
            5'd13:j_1<=game13;
            5'd14:j_1<=game14;
            5'd15:j_1<=game15;
            5'd16:j_1<=game16;
            5'd17:j_1<=game17;
            5'd18:j_1<=game18;
            5'd19:j_1<=game19;
            5'd20:j_1<=game20;
            5'd21:j_1<=game21;
            5'd22:j_1<=game22;
            5'd23:j_1<=game23;
            endcase
            case(j)
            5'd0:j0<=game0;
            5'd1:j0<=game1;
            5'd2:j0<=game2;
            5'd3:j0<=game3;
            5'd4:j0<=game4;
            5'd5:j0<=game5;
            5'd6:j0<=game6;
            5'd7:j0<=game7;
            5'd8:j0<=game8;
            5'd9:j0<=game9;
            5'd10:j0<=game10;
            5'd11:j0<=game11;
            5'd12:j0<=game12;
            5'd13:j0<=game13;
            5'd14:j0<=game14;
            5'd15:j0<=game15;
            5'd16:j0<=game16;
            5'd17:j0<=game17;
            5'd18:j0<=game18;
            5'd19:j0<=game19;
            5'd20:j0<=game20;
            5'd21:j0<=game21;
            5'd22:j0<=game22;
            5'd23:j0<=game23;
            endcase
            case(j+1)
            5'd0:j1<=game0;
            5'd1:j1<=game1;
            5'd2:j1<=game2;
            5'd3:j1<=game3;
            5'd4:j1<=game4;
            5'd5:j1<=game5;
            5'd6:j1<=game6;
            5'd7:j1<=game7;
            5'd8:j1<=game8;
            5'd9:j1<=game9;
            5'd10:j1<=game10;
            5'd11:j1<=game11;
            5'd12:j1<=game12;
            5'd13:j1<=game13;
            5'd14:j1<=game14;
            5'd15:j1<=game15;
            5'd16:j1<=game16;
            5'd17:j1<=game17;
            5'd18:j1<=game18;
            5'd19:j1<=game19;
            5'd20:j1<=game20;
            5'd21:j1<=game21;
            5'd22:j1<=game22;
            5'd23:j1<=game23;
            endcase
            case(j+2)
            5'd0:j2<=game0;
            5'd1:j2<=game1;
            5'd2:j2<=game2;
            5'd3:j2<=game3;
            5'd4:j2<=game4;
            5'd5:j2<=game5;
            5'd6:j2<=game6;
            5'd7:j2<=game7;
            5'd8:j2<=game8;
            5'd9:j2<=game9;
            5'd10:j2<=game10;
            5'd11:j2<=game11;
            5'd12:j2<=game12;
            5'd13:j2<=game13;
            5'd14:j2<=game14;
            5'd15:j2<=game15;
            5'd16:j2<=game16;
            5'd17:j2<=game17;
            5'd18:j2<=game18;
            5'd19:j2<=game19;
            5'd20:j2<=game20;
            5'd21:j2<=game21;
            5'd22:j2<=game22;
            5'd23:j2<=game23;
            endcase
            case(j+3)
            5'd0:j3<=game0;
            5'd1:j3<=game1;
            5'd2:j3<=game2;
            5'd3:j3<=game3;
            5'd4:j3<=game4;
            5'd5:j3<=game5;
            5'd6:j3<=game6;
            5'd7:j3<=game7;
            5'd8:j3<=game8;
            5'd9:j3<=game9;
            5'd10:j3<=game10;
            5'd11:j3<=game11;
            5'd12:j3<=game12;
            5'd13:j3<=game13;
            5'd14:j3<=game14;
            5'd15:j3<=game15;
            5'd16:j3<=game16;
            5'd17:j3<=game17;
            5'd18:j3<=game18;
            5'd19:j3<=game19;
            5'd20:j3<=game20;
            5'd21:j3<=game21;
            5'd22:j3<=game22;
            5'd23:j3<=game23;
            endcase
            new_block_1<=blocks;
            new_i_1<=i;
            new_j_1<=j;
        if(start)
        begin
            //旋转变化
            if(handle==0)
            begin
                case(blocks)
                5'd0:
                begin
                    new_block_1<=5'd0;
                end
                5'd1:
                begin
                    j0[i+1]<=1;
                    j_1[i+1]<=1;
                    j0[i-1]<=1;
                    j1[i]<=0;
                    j_1[i]<=0;
                    j1[i+1]<=0;
                    new_block_1<=5'd2;
                end 
                5'd2:
                begin
                    j1[i]<=1;
                    j_1[i]<=1;
                    j_1[i-1]<=1;
                    j0[i-1]<=0;
                    j0[i+1]<=0;
                    j_1[i+1]<=0;
                    new_block_1<=5'd3;
                end 
                5'd3:
                begin
                    j0[i+1]<=1;
                    j1[i-1]<=1;
                    j0[i-1]<=1;
                    j1[i]<=0;
                    j_1[i]<=0;
                    j_1[i-1]<=0;
                    new_block_1<=5'd4;
                end 
                5'd4:
                begin
                    j1[i]<=1;
                    j_1[i]<=1;
                    j1[i+1]<=1;
                    j1[i-1]<=0;
                    j0[i-1]<=0;
                    j0[i+1]<=0;
                    new_block_1<=5'd1;
                end 
                5'd5:
                begin
                    j0[i+1]<=1;
                    j1[i+1]<=1;
                    j0[i-1]<=1;
                    j1[i]<=0;
                    j_1[i]<=0;
                    j1[i-1]<=0;
                    new_block_1<=5'd6;
                end 
                5'd6:
                begin
                    j_1[i+1]<=1;
                    j_1[i]<=1;
                    j1[i]<=1;
                    j1[i+1]<=0;
                    j0[i-1]<=0;
                    j0[i+1]<=0;
                    new_block_1<=5'd7;
                end 
                5'd7:
                begin
                    j0[i+1]<=1;
                    j_1[i-1]<=1;
                    j0[i-1]<=1;
                    j1[i]<=0;
                    j_1[i]<=0;
                    j_1[i+1]<=0;
                    new_block_1<=5'd8;
                end 
                5'd8:
                begin
                    j_1[i]<=1;
                    j1[i]<=1;
                    j1[i-1]<=1;
                    j0[i+1]<=0;
                    j0[i-1]<=0;
                    j_1[i-1]<=0;
                    new_block_1<=5'd5;
                end 
                5'd9:
                begin
                    j0[i+1]<=1;
                    j0[i+2]<=1;
                    j0[i-1]<=1;
                    j1[i]<=0;
                    j_1[i]<=0;
                    j2[i]<=0;
                    new_block_1<=5'd10;
                end 
                5'd10:
                begin
                    j_2[i]<=1;
                    j_1[i]<=1;
                    j1[i]<=1;
                    j0[i+1]<=0;
                    j0[i+2]<=0;
                    j0[i-1]<=0;
                    new_block_1<=5'd9;
                end 
                5'd11:
                begin
                    j1[i]<=1;
                    j0[i+1]<=0;
                    new_block_1<=5'd12;
                end 
                5'd12:
                begin
                    j0[i+1]<=1;
                    j_1[i]<=0;
                    new_block_1<=5'd13;
                end 
                5'd13:
                begin
                    j_1[i]<=1;
                    j0[i-1]<=0;
                    new_block_1<=5'd14;
                end 
                5'd14:
                begin
                    j0[i-1]<=1;
                    j_1[i]<=0;
                    new_block_1<=5'd11;
                end 
                5'd15:
                begin
                    j1[i]<=1;
                    j1[i+1]<=1;
                    j_1[i]<=0;
                    j1[i-1]<=0;
                    new_block_1<=5'd16;
                end 
                5'd16:
                begin
                    j1[i-1]<=1;
                    j_1[i]<=1;
                    j1[i]<=0;
                    j1[i+1]<=0;
                    new_block_1<=5'd15;
                end 
                5'd17:
                begin
                    j_1[i+1]<=1;
                    j0[i-1]<=1;
                    j0[i+1]<=0;
                    j1[i+1]<=0;
                    new_block_1<=5'd18;
                end
                5'd18:
                begin
                    j0[i+1]<=1;
                    j1[i+1]<=1;
                    j_1[i+1]<=0;
                    j0[i-1]<=0;
                    new_block_1<=5'd17;
                end 
                endcase
            end

            //左移一格
            else if(handle==1)
            begin
                new_i_1<=i-1;
                case(blocks)
                5'd0:
                begin
                    j0[i-1]<=1;
                    j1[i-1]<=1;
                    j0[i]<=1;
                    j1[i]<=1;
                    j1[i+1]<=0;
                    j0[i+1]<=0;
                end
                5'd1:
                begin
                    j_1[i-1]<=1;
                    j0[i-1]<=1;
                    j1[i-1]<=1;
                    j1[i]<=1;
                    j0[i]<=0;
                    j_1[i]<=0;
                    j1[i+1]<=0;
                end 
                5'd2:
                begin
                    j0[i-2]<=1;
                    j_1[i]<=1;
                    j0[i]<=1;
                    j0[i+1]<=1;
                    j0[i+1]<=0;
                    j_1[i+1]<=0;
                end
                5'd3:
                begin
                    j_1[i-2]<=1;
                    j0[i-1]<=1;
                    j1[i-1]<=1;
                    j_1[i-1]<=1;
                    j0[i]<=0;
                    j_1[i]<=0;
                    j1[i]<=0;
                end
                5'd4:
                begin
                    j0[i-2]<=1;
                    j1[i-2]<=1;
                    j0[i]<=1;
                    j0[i-1]<=1;
                    j0[i+1]<=0;
                    j1[i-1]<=0;
                end
                5'd5:
                begin
                    j1[i-2]<=1;
                    j0[i-1]<=1;
                    j_1[i-1]<=1;
                    j1[i-1]<=1;
                    j0[i]<=0;
                    j_1[i]<=0;
                    j1[i]<=0;
                end
                5'd6:
                begin
                    j0[i-2]<=1;
                    j1[i]<=1;
                    j0[i]<=1;
                    j0[i-1]<=1;
                    j0[i+1]<=0;
                    j1[i+1]<=0;
                end
                5'd7:
                begin
                    j1[i-1]<=1;
                    j0[i-1]<=1;
                    j_1[i-1]<=1;
                    j_1[i]<=1;
                    j0[i]<=0;
                    j_1[i+1]<=0;
                    j1[i]<=0;
                end
                5'd8:
                begin
                    j0[i-2]<=1;
                    j_1[i-2]<=1;
                    j0[i]<=1;
                    j0[i-1]<=1;
                    j_1[i-1]<=0;
                    j0[i+1]<=0;
                end
                5'd9:
                begin
                    j1[i-1]<=1;
                    j0[i-1]<=1;
                    j_1[i-1]<=1;
                    j2[i-1]<=1;
                    j0[i]<=0;
                    j_1[i]<=0;
                    j1[i]<=0;
                    j2[i]<=0;
                end
                5'd10:
                begin
                    j0[i-2]<=1;
                    j0[i-1]<=1;
                    j0[i]<=1;
                    j0[i+1]<=1;
                    j0[i+2]<=0;
                end
                5'd11:
                begin
                    j_1[i-1]<=1;
                    j0[i-2]<=1;
                    j0[i]<=1;
                    j0[i-1]<=1;
                    j_1[i]<=0;
                    j0[i+1]<=0;
                end
                5'd12:
                begin
                    j1[i-1]<=1;
                    j0[i-2]<=1;
                    j_1[i-1]<=1;
                    j0[i-1]<=1;
                    j0[i]<=0;
                    j_1[i]<=0;
                    j1[i]<=0;
                end
                5'd13:
                begin
                    j1[i-1]<=1;
                    j0[i-2]<=1;
                    j0[i]<=1;
                    j0[i-1]<=1;
                    j0[i+1]<=0;
                    j1[i]<=0;
                end
                5'd14:
                begin
                    j1[i-1]<=1;
                    j0[i-1]<=1;
                    j_1[i-1]<=1;
                    j0[i]<=1;
                    j1[i]<=0;
                    j_1[i]<=0;
                    j0[i+1]<=0;
                end
                5'd15:
                begin
                    j1[i-2]<=1;
                    j0[i-2]<=1;
                    j_1[i-1]<=1;
                    j0[i-1]<=1;
                    j0[i]<=0;
                    j_1[i]<=0;
                    j1[i-1]<=0;
                end
                5'd16:
                begin
                    j1[i-1]<=1;
                    j0[i-2]<=1;
                    j0[i-1]<=1;
                    j1[i]<=1;
                    j0[i]<=0;
                    j1[i+1]<=0;
                end
                5'd17:
                begin
                    j1[i]<=1;
                    j0[i-1]<=1;
                    j_1[i-1]<=1;
                    j0[i]<=1;
                    j0[i+1]<=0;
                    j1[i+1]<=0;
                    j_1[i]<=0;
                end
                5'd18:
                begin
                    j_1[i-1]<=1;
                    j0[i-2]<=1;
                    j0[i-1]<=1;
                    j_1[i]<=1;
                    j0[i]<=0;
                    j_1[i+1]<=0;
                end
                endcase
            end

            //右移一格
            else if(handle==2)
            begin
                new_i_1<=i+1;
                case(blocks)
                5'd0:
                begin
                    j1[i+2]<=1;
                    j0[i+2]<=1;
                    j0[i]<=0;
                    j1[i]<=0;
                end
                5'd1:
                begin
                    j1[i+2]<=1;
                    j0[i+1]<=1;
                    j_1[i+1]<=1;
                    j_1[i]<=0;
                    j0[i]<=0;
                    j1[i]<=0;
                end
                5'd2:
                begin
                    j_1[i+2]<=1;
                    j0[i+2]<=1;
                    j0[i-1]<=0;
                    j_1[i+1]<=0;
                end
                5'd3:
                begin
                    j1[i+1]<=1;
                    j0[i+1]<=1;
                    j_1[i+1]<=1;
                    j_1[i-1]<=0;
                    j0[i]<=0;
                    j1[i]<=0;
                end
                5'd4:
                begin
                    j1[i]<=1;
                    j0[i+2]<=1;
                    j0[i-1]<=0;
                    j1[i-1]<=0;
                end
                5'd5:
                begin
                    j1[i+1]<=1;
                    j0[i+1]<=1;
                    j_1[i+1]<=1;
                    j1[i-1]<=0;
                    j0[i]<=0;
                    j_1[i]<=0;
                end
                5'd6:
                begin
                    j1[i+2]<=1;
                    j0[i+2]<=1;
                    j0[i-1]<=0;
                    j1[i+1]<=0;
                end
                5'd7:
                begin
                    j1[i+1]<=1;
                    j0[i+1]<=1;
                    j_1[i+2]<=1;
                    j1[i]<=0;
                    j0[i]<=0;
                    j_1[i]<=0;
                end
                5'd8:
                begin
                    j_1[i]<=1;
                    j0[i+2]<=1;
                    j0[i-1]<=0;
                    j_1[i-1]<=0;
                end
                5'd9:
                begin
                    j1[i+1]<=1;
                    j0[i+1]<=1;
                    j2[i+1]<=1;
                    j_1[i+1]<=1;
                    j1[i]<=0;
                    j0[i]<=0;
                    j_1[i]<=0;
                    j2[i]<=0;
                end
                5'd10:
                begin
                    j0[i+3]<=1;
                    j0[i-1]<=0;
                end
                5'd11:
                begin
                    j_1[i+1]<=1;
                    j0[i+2]<=1;
                    j_1[i]<=0;
                    j0[i-1]<=0;
                end
                5'd12:
                begin
                    j1[i+1]<=1;
                    j0[i+1]<=1;
                    j_1[i+1]<=1;
                    j1[i]<=0;
                    j0[i-1]<=0;
                    j_1[i]<=0;
                end
                5'd13:
                begin
                    j1[i+1]<=1;
                    j0[i+2]<=1;
                    j0[i-1]<=0;
                    j1[i]<=0;
                end
                5'd14:
                begin
                    j1[i+1]<=1;
                    j0[i+2]<=1;
                    j_1[i+1]<=1;
                    j1[i]<=0;
                    j0[i]<=0;
                    j_1[i]<=0;
                end
                5'd15:
                begin
                    j1[i]<=1;
                    j0[i+1]<=1;
                    j_1[i+1]<=1;
                    j1[i-1]<=0;
                    j_1[i]<=0;
                    j0[i-1]<=0;
                end
                5'd16:
                begin
                    j1[i+2]<=1;
                    j0[i+1]<=1;
                    j0[i-1]<=0;
                    j1[i]<=0;
                end
                5'd17:
                begin
                    j1[i+2]<=1;
                    j0[i+2]<=1;
                    j_1[i+1]<=1;
                    j_1[i]<=0;
                    j1[i+1]<=0;
                    j0[i]<=0;
                end
                5'd18:
                begin
                    j_1[i+2]<=1;
                    j0[i+1]<=1;
                    j_1[i]<=0;
                    j0[i-1]<=0;
                end
                endcase
            end 
        end
        if(clk0)
        begin
            case(blocks)
            5'd0:
            begin
                if((j2[i]==0)&&(j2[i+1]==0)&&(j<21))
                begin
                    j0[i]<=0;
                    j0[i+1]<=0;
                    j2[i]<=1;
                    j2[i+1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            5'd1:
            begin
                if((j2[i]==0)&&(j2[i+1]==0)&&(j<21))
                begin
                    j_1[i]<=0;
                    j1[i+1]<=0;
                    j2[i]<=1;
                    j2[i+1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end   
                else handle_finish_1<=1; 
            end
            5'd2:
            begin
                if((j1[i]==0)&&(j1[i+1]==0)&&(j1[i-1]==0)&&(j<22))
                begin
                    j_1[i+1]<=0;
                    j0[i]<=0;
                    j0[i-1]<=0;
                    j1[i+1]<=1;
                    j1[i]<=1;
                    j1[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end 
                else handle_finish_1<=1;   
            end
            5'd3:
            begin
                if((j2[i]==0)&&(j0[i-1]==0)&&(j<21))
                begin
                    j_1[i]<=0;
                    j_1[i-1]<=0;
                    j2[i]<=1;
                    j0[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            5'd4:
            begin
                if((j1[i]==0)&&(j1[i+1]==0)&&(j2[i-1]==0)&&(j<21))
                begin
                    j0[i+1]<=0;
                    j0[i]<=0;
                    j0[i-1]<=0;
                    j1[i+1]<=1;
                    j1[i]<=1;
                    j2[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end 
                else handle_finish_1<=1;   
            end
            5'd5:
            begin
                if((j2[i]==0)&&(j2[i-1]==0)&&(j<21))
                begin
                    j_1[i]<=0;
                    j1[i-1]<=0;
                    j2[i]<=1;
                    j2[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end   
                else handle_finish_1<=1; 
            end
            5'd6:
            begin
                if((j1[i]==0)&&(j2[i+1]==0)&&(j1[i-1]==0)&&(j<21))
                begin
                    j0[i+1]<=0;
                    j0[i]<=0;
                    j0[i-1]<=0;
                    j2[i+1]<=1;
                    j1[i]<=1;
                    j1[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            5'd7:
            begin
                if((j2[i]==0)&&(j0[i+1]==0)&&(j<21))
                begin
                    j_1[i]<=0;
                    j_1[i+1]<=0;
                    j2[i]<=1;
                    j0[i+1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end   
                else handle_finish_1<=1; 
            end
            5'd8:
            begin
                if((j1[i]==0)&&(j1[i+1]==0)&&(j1[i-1]==0)&&(j<22))
                begin
                    j0[i+1]<=0;
                    j0[i]<=0;
                    j_1[i-1]<=0;
                    j1[i+1]<=1;
                    j1[i]<=1;
                    j1[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            5'd9:
            begin
                if((j3[i]==0)&&(j<20))
                begin
                    j_1[i]<=0;
                    j3[i]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            5'd10:
            begin
                if((j1[i]==0)&&(j1[i+1]==0)&&(j1[i-1]==0)&&(j1[i+2]==0)&&(j<22))
                begin
                    j0[i+1]<=0;
                    j0[i]<=0;
                    j0[i-1]<=0;
                    j0[i+2]<=0;
                    j1[i+1]<=1;
                    j1[i]<=1;
                    j1[i-1]<=1;
                    j1[i+2]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            5'd11:
            begin
                if((j1[i]==0)&&(j1[i+1]==0)&&(j1[i-1]==0)&&(j<22))
                begin
                    j0[i+1]<=0;
                    j_1[i]<=0;
                    j0[i-1]<=0;
                    j1[i+1]<=1;
                    j0[i+1]<=1;
                    j_1[i+1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            5'd12:
            begin
                if((j2[i]==0)&&(j1[i-1]==0)&&(j<21))
                begin
                    j_1[i]<=0;
                    j0[i-1]<=0;
                    j2[i]<=1;
                    j1[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end   
                else handle_finish_1<=1; 
            end
            5'd13:
            begin
                if((j2[i]==0)&&(j1[i+1]==0)&&(j1[i-1]==0)&&(j<21))
                begin
                    j0[i+1]<=0;
                    j0[i]<=0;
                    j0[i-1]<=0;
                    j1[i+1]<=1;
                    j0[i+2]<=1;
                    j1[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            5'd14:
            begin
                if((j2[i]==0)&&(j1[i+1]==0)&&(j<21))
                begin
                    j_1[i]<=0;
                    j0[i+1]<=0;
                    j2[i]<=1;
                    j1[i+1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end   
                else handle_finish_1<=1; 
            end
            5'd15:
            begin
                if((j1[i]==0)&&(j2[i-1]==0)&&(j<21))
                begin
                    j_1[i]<=0;
                    j0[i-1]<=0;
                    j1[i]<=1;
                    j2[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end   
                else handle_finish_1<=1; 
            end
            5'd16:
            begin
                if((j2[i]==0)&&(j2[i+1]==0)&&(j1[i-1]==0)&&(j<21))
                begin
                    j1[i+1]<=0;
                    j0[i]<=0;
                    j0[i-1]<=0;
                    j2[i+1]<=1;
                    j2[i]<=1;
                    j1[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            5'd17:
            begin
                if((j1[i]==0)&&(j2[i+1]==0)&&(j<21))
                begin
                    j_1[i]<=0;
                    j0[i+1]<=0;
                    j1[i]<=1;
                    j2[i+1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end   
                else handle_finish_1<=1; 
            end
            5'd18:
            begin
                if((j1[i]==0)&&(j0[i+1]==0)&&(j1[i-1]==0)&&(j<22))
                begin
                    j_1[i+1]<=0;
                    j0[i-1]<=0;
                    j1[i-1]<=0;
                    j1[i]<=1;
                    j0[i+1]<=1;
                    j1[i-1]<=1;
                    new_j_1<=j+1;
                    handle_finish_1<=0;
                end
                else handle_finish_1<=1;    
            end
            endcase
        end
        case(j)
            5'd4:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=j_2;
                game3_1<=j_1;
                game4_1<=j0;
                game5_1<=j1;
                game6_1<=j2;
                game7_1<=j3;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd5:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=j_2;
                game4_1<=j_1;
                game5_1<=j0;
                game6_1<=j1;
                game7_1<=j2;
                game8_1<=j3;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd6:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=j_2;
                game5_1<=j_1;
                game6_1<=j0;
                game7_1<=j1;
                game8_1<=j2;
                game9_1<=j3;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd7:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=j_2;
                game6_1<=j_1;
                game7_1<=j0;
                game8_1<=j1;
                game9_1<=j2;
                game10_1<=j3;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd8:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=j_2;
                game7_1<=j_1;
                game8_1<=j0;
                game9_1<=j1;
                game10_1<=j2;
                game11_1<=j3;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd9:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=j_2;
                game8_1<=j_1;
                game9_1<=j0;
                game10_1<=j1;
                game11_1<=j2;
                game12_1<=j3;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd10:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=j_2;
                game9_1<=j_1;
                game10_1<=j0;
                game11_1<=j1;
                game12_1<=j2;
                game13_1<=j3;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd11:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=j_2;
                game10_1<=j_1;
                game11_1<=j0;
                game12_1<=j1;
                game13_1<=j2;
                game14_1<=j3;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd12:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=j_2;
                game11_1<=j_1;
                game12_1<=j0;
                game13_1<=j1;
                game14_1<=j2;
                game15_1<=j3;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd13:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=j_2;
                game12_1<=j_1;
                game13_1<=j0;
                game14_1<=j1;
                game15_1<=j2;
                game16_1<=j3;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd14:begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=j_2;
                game13_1<=j_1;
                game14_1<=j0;
                game15_1<=j1;
                game16_1<=j2;
                game17_1<=j3;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd15:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=j_2;
                game14_1<=j_1;
                game15_1<=j0;
                game16_1<=j1;
                game17_1<=j2;
                game18_1<=j3;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd16:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=j_2;
                game15_1<=j_1;
                game16_1<=j0;
                game17_1<=j1;
                game18_1<=j2;
                game19_1<=j3;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd17:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=j_2;
                game16_1<=j_1;
                game17_1<=j0;
                game18_1<=j1;
                game19_1<=j2;
                game20_1<=j3;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd18:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=j_2;
                game17_1<=j_1;
                game18_1<=j0;
                game19_1<=j1;
                game20_1<=j2;
                game21_1<=j3;
                game22_1<=game22;
                game23_1<=game23;
            end
            5'd19:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=j_2;
                game18_1<=j_1;
                game19_1<=j0;
                game20_1<=j1;
                game21_1<=j2;
                game22_1<=j3;
                game23_1<=game23;
            end
            5'd20:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=j_2;
                game19_1<=j_1;
                game20_1<=j0;
                game21_1<=j1;
                game22_1<=j2;
                game23_1<=j3;
            end
            5'd21:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=j_2;
                game20_1<=j_1;
                game21_1<=j0;
                game22_1<=j1;
                game23_1<=j2;
            end
            5'd22:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=j_2;
                game21_1<=j_1;
                game22_1<=j0;
                game23_1<=j1;
            end
            default:
            begin
                game0_1<=game0;
                game1_1<=game1;
                game2_1<=game2;
                game3_1<=game3;
                game4_1<=game4;
                game5_1<=game5;
                game6_1<=game6;
                game7_1<=game7;
                game8_1<=game8;
                game9_1<=game9;
                game10_1<=game10;
                game11_1<=game11;
                game12_1<=game12;
                game13_1<=game13;
                game14_1<=game14;
                game15_1<=game15;
                game16_1<=game16;
                game17_1<=game17;
                game18_1<=game18;
                game19_1<=game19;
                game20_1<=game20;
                game21_1<=game21;
                game22_1<=game22;
                game23_1<=game23;
            end
        endcase
        handle_finish<=handle_finish_1;
        new_block<=new_block_1;
        new_i<=new_i_1;
        new_j<=new_j_1;
    end
endmodule